// This file is generated by Slice Machine. Update with care!

import MySlice from './MySlice';
import Posts from './Posts';

export {
	MySlice,
	Posts,
};

export const components = {
	my_slice: MySlice,
	posts: Posts,
};
